### ISSUE TITLE
Mirror Network Integration does not work with Mirror v2.0.0 or more

### ISSUE THREAD

**Issue by shiena** [Placeholder-Software/Dissonance#146]
## Context

Mirror v2.0.0 has breaking changes in https://github.com/vis2k/Mirror/pull/650

## Expected Behavior

No compilation errors

## Actual Behavior

![image](https://user-images.githubusercontent.com/1295639/55276689-d008f500-5339-11e9-9458-64445fd78c06.png)

## Workaround

use `NetworkClient` instead of `NetworkManager.singleton.client`

## Fix

Same as workaround

## Steps to Reproduce
_Provide a detailed set of steps to reproduce the problem_
1. Create a new unity project
2. Import Mirror v3.0.1
3. Import Dissonance v6.3.1
4. Import Dissonance Mirror Network Integration v6.3.4

## Your Environment

- **Dissonance version used**:  v6.3.1

- **Dissonance Mirror Network Integration version**:  v6.3.4

- **Unity version**: 2018.3.11f1

- **Mirror version**: v3.0.1

**Comment by martindevans** [comment]
For now it looks like your workaround should do the job.

I plan to release an update to the integration with fixes for this and a load of other things that have been obsoleted as soon as these changes get released to the asset store version of Mirror. My general plan is to track the asset store version of Mirror for Dissonance compatibility , rather than trying to keep up with the daily changes being made in master!

**Comment by martindevans** [comment]
A new version of Mirror has just been published to the asset store, I've just uploaded an updated version of the [Dissonance MirrorIgnorance integration package](https://placeholder-software.co.uk/dissonance/integrations/6.3.1/Dissonance-MirrorIgnorance-6.3.4.unitypackage) which should be compatible with the new version on the asset store.

**Comment by shiena** [comment]
I have updated the MirrorIgnorance integration package from 6.3.4 to 6.3.5. But the difference is only json and meta.

```diff
diff --git a/Assets/Dissonance/Integrations.meta b/Assets/Dissonance/Integrations.meta
index c5bf624..4348410 100644
--- a/Assets/Dissonance/Integrations.meta
+++ b/Assets/Dissonance/Integrations.meta
@@ -1,8 +1,9 @@
 fileFormatVersion: 2
 guid: 9cba40eade2d300428cb443d5b09ed69
 folderAsset: yes
+timeCreated: 1471878564
+licenseType: Free
 DefaultImporter:
-  externalObjects: {}
   userData:
   assetBundleName:
   assetBundleVariant:
diff --git a/Assets/Dissonance/Integrations/MirrorIgnorance/dissonance-integration-metadata.json b/Assets/Dissonance/Integrations/MirrorIgnorance/dissonance-integration-metadata.json
index 8f64dbd..7faab4f 100644
--- a/Assets/Dissonance/Integrations/MirrorIgnorance/dissonance-integration-metadata.json
+++ b/Assets/Dissonance/Integrations/MirrorIgnorance/dissonance-integration-metadata.json
@@ -3,6 +3,6 @@
     "_releasedWith": {
         "_major": 6,
         "_minor": 3,
-        "_patch": 4
+        "_patch": 5
     }
 }
\ No newline at end of file
```

**Comment by martindevans** [comment]
Sorry about that, I must have messed up the build/release process somehow. I'll update it right now and post another comment here when done.

**Comment by martindevans** [comment]
I've uploaded another package here: https://placeholder-software.co.uk/dissonance/integrations/6.3.1/Dissonance-MirrorIgnorance-6.3.6.unitypackage

**Comment by shiena** [comment]
Thanks! it works well with Mirror 3.4.5.

**Comment by martindevans** [comment]
Excellent, thanks for confirming that :)
